### PR TITLE
upgrade to m3

### PR DESCRIPTION
**Pull request by longnguyen11288**

### CODE REVIEW

**Comment by drnic** [comment]
@longnguyen11288 as I said on kato, `m3.medium` is too small for a microbosh - its ephemeral disk is only 4G. If we're abandoning `m1.medium` then either `m3.large` or a different instance type family.

**Comment by longnguyen11288** [comment]
I added 160gb ephermal disk. I tested it and all tmp data goes to that disk

**Comment by drnic** [comment]
Ahhh awesome that this works.

**Comment by drnic** [comment]
Merge away

**Comment by drnic** [comment]
Except for the failing tests. What's up?

**Comment by longnguyen11288** [comment]
The terrible gem is whats up... locking down

**Pull request merged**
