### PR TITLE
add the resurrector to the AWS provider by default

### PR DESCRIPTION
**Pull request by teancom**
I only added it to the AWS provider, as that's the only one that I could personally test.

### CODE REVIEW

**Comment by longnguyen11288** [comment]
+1

**Comment by drnic** [comment]
Add the equivalent changes to OpenStack as well. 

@mstine do you think vSphere bosh also needs resurrector?

**Comment by teancom** [comment]
It was already in the openstack provider, @drnic. You added it, actually:

```
$ git blame lib/bosh-bootstrap/microbosh_providers/openstack.rb | grep resurrector
341d58f2 (Dr Nic Williams                  2013-10-26 13:20:34 -0700  23)             "hm"=>{"resurrector_enabled" => true},
```

**Comment by drnic** [comment]
Go me!

**Pull request merged**
