### PR TITLE
switch to m3.medium instance type (m1.medium no longer available)

### PR DESCRIPTION
**Pull request by thewoolleyman**

### CODE REVIEW

**Comment by drnic** [comment]
We can't use m3.medium due to its tiny ephemeral disk (4G). Annoying. So m3.large?

**Comment by thewoolleyman** [comment]
I would go with c3.large, it's more resources (except for memory) than m3.large, and cheaper.

Also, https://github.com/cloudfoundry-community/terraform-aws-bosh/pull/2 is a companion pull request.

Would you like me to update both of these with new pull requests, or do you just want to make the changes?

**Comment by thewoolleyman** [comment]
Wait, so m3.medium should be ok for cloudfoundry-community/terraform-aws-bosh#2 - since that's just the bastion.  Right?

**Comment by longnguyen11288** [comment]
Hey so I added m3 with ephemeral disk so it should defaulted to m3 now .

**Pull request closed without merging**
